
%delete ('../images/*.*');

%--------------------------------------------------------------------------------------

F = FigureStruct();
F.Caption = '';
F.FigData =  {  'Name','ChokedFlow',...
                                    'Scale',0.65,...
                                    'FontSize',9,...
                                    'Title', 'ChokedFlow',...
                                    'Directory','../imgperm',...
                                    'float',false,...
                                    'placement','H';
                                    };
F.ImagesNames ={ '../imgperm/ChokedFlow.png'};
FigureR10(F);

%--------------------------------------------------------------------------------------

F = FigureStruct();
F.Caption = '';
F.FigData =  {  'Name','FullFlowAntiBoundary',...
                                    'Scale',0.65,...
                                    'FontSize',9,...
                                    'Title', 'Dobule Cone',...
                                    'Directory','../imgperm',...
                                    'float',false,...
                                    'placement','H';
                                    };
F.ImagesNames ={ '../imgperm/FullFlowAntiBoundary.png'};
FigureR10(F);

%--------------------------------------------------------------------------------------

F = FigureStruct();
F.Caption = '';
F.FigData =  {  'Name','FullFlowSlice',...
                                    'Scale',0.35,...
                                    'FontSize',9,...
                                    'Title', 'Dobule Cone',...
                                    'Directory','../imgperm',...
                                    'float',false,...
                                    'placement','H';
                                    };
F.ImagesNames ={ '../imgperm/FullFlowSlice.png'};
FigureR10(F);

%--------------------------------------------------------------------------------------
PW1 = "../imgperm/Slide1.png";
PW2 = "../imgperm/Slide2.png";
PW3 = "../imgperm/Slide3.png";
PW4 = "../imgperm/Slide4.png";
PW5 = "../imgperm/Slide5.png";
PW6 = "../imgperm/Slide6.png";
PW7 = "../imgperm/Slide7.png";
PW8 = "../imgperm/Slide8.png";
PW9 = "../imgperm/Slide9.png";
PW10 = "../imgperm/Slide10.png";
SC1 = "Time 1";
SC2 = "Time 2";
SC3 = "Time 3";
SC4 = "Time 4";
SC5 = "Time 5";
SC6 = "Time 6";
SC7 = "Time 7";
SC8 = "Time 8";
SC9 = "Time 9";
SC10 = "Time 10";
LBL1 = "Slide1";
LBL2 = "Slide2";
LBL3 = "Slide3";
LBL4 = "Slide4";
LBL5 = "Slide5";
LBL6 = "Slide6";
LBL7 = "Slide7";
LBL8 = "Slide8";
LBL9 = "Slide9";
LBL10 = "Slide10";

ImageThesisR10('FullFlow',...
                    {PW1,PW2,PW3,PW4,PW5,PW6,PW7,PW8,PW9,PW10},...
                    {SC1,SC2,SC3,SC4,SC5,SC6,SC7,SC8,SC9,SC10},...    
                    {LBL1,LBL2,LBL3,LBL4,LBL5,LBL6,LBL7,LBL8,LBL9,LBL10},...
                    'Full Flow',...
                    '../imgperm',...
                    0.35,...
                    [2,5],...
                    'ht',...
                    true);
%--------------------------------------------------------------------------------------
PW1 = "../imgperm/SimpVectPlotAll.png";
PW2 = "../imgperm/SimpVectPlotTop.png";
PW3 = "../imgperm/SimpVectPlotFiltered.png";
PW4 = "../imgperm/SimpVectPlotFilteredGran.png";
SC1 = "Simple flow plot showing all particles ";
SC2 = "Simple flow plot focued on the top of the flow with vectors scaled.";
SC3 = "Simple flow plot with vectors filtered from 320 to 340 degrees and from 20 to 40 degrees are filtered.";
SC4 = "Simple flow plot with vectors filtered from 320 to 340 degrees and from 20 to 40 degrees are filtered. The plot shows only these vectors but in this plot the granularity has been set to 1.0.";
LBL1 = "SimpVectPlot01";
LBL2 = "SimpVectPlot02";
LBL3 = "SimpVectPlot03";
LBL4 = "SimpVectPlot04";


ImageThesisR10('SimpVectPlot',...
                    {PW1,PW2,PW3,PW4},...
                    {SC1,SC2,SC3,SC4},...    
                    {LBL1,LBL2,LBL3,LBL4},...
                    'test',...
                    '../imgperm',...
                    0.35,...
                    [2,2],...
                    'ht',...
                    true);
%--------------------------------------------------------------------------------------
%-------------------------------------------------------------------------------------
if 0
F = FigureStruct();
F.Caption = '';
F.FigData =  {  'Name','SimpVectPlotFilteredGran',...
                                    'Scale',0.35,...
                                    'FontSize',9,...
                                    'Title', 'Dobule Cone',...
                                    'Directory','../imgperm',...
                                    'float',false,...
                                    'placement','H';
                                    };
F.ImagesNames ={ '../imgperm/SimpVectPlotFilteredGran.png'};
FigureR10(F);

%--------------------------------------------------------------------------------------

F = FigureStruct();
F.Caption = '';
F.FigData =  {  'Name','SimpVectPlotFiltered',...
                                    'Scale',0.35,...
                                    'FontSize',9,...
                                    'Title', 'Dobule Cone',...
                                    'Directory','../imgperm',...
                                    'float',false,...
                                    'placement','H';
                                    };
F.ImagesNames ={ '../imgperm/SimpVectPlotFiltered.png'};
FigureR10(F);

%--------------------------------------------------------------------------------------
F = FigureStruct();
F.Caption = '';
F.FigData =  {  'Name','SimpVectPlotTop',...
                                    'Scale',0.35,...
                                    'FontSize',9,...
                                    'Title', 'Dobule Cone',...
                                    'Directory','../imgperm',...
                                    'float',false,...
                                    'placement','H';
                                    };
F.ImagesNames ={ '../imgperm/SimpVectPlotTop.png'};
FigureR10(F)

%--------------------------------------------------------------------------------------
F = FigureStruct();
F.Caption = '';
F.FigData =  {  'Name','SimpVectPlotAll',...
                                    'Scale',0.35,...
                                    'FontSize',9,...
                                    'Title', 'Dobule Cone',...
                                    'Directory','../imgperm',...
                                    'float',false,...
                                    'placement','H';
                                    };
F.ImagesNames ={ '../imgperm/SimpVectPlotAll.png'};
FigureR10(F);
end
%--------------------------------------------------------------------------------------
PW1 = "../imgperm/SimpleSim001.png";
PW2 = "../imgperm/SimpleSim002.png";
PW3 = "../imgperm/SimpleSim003.png";
PW4 = "../imgperm/SimpleSim004.png";
PW5 = "../imgperm/SimpleSim005.png";
SC1 = "Starting flow for the simple sequence shows the particles advancing with the boundary active.";
SC2 = "Same flow with boundary disabled.";
SC3 = "Flow proceeds down nozzle.";
SC4 = "Flow begins to reflect of of the sloping section of the nozzle.";
SC5 = "Flow reflects off of sloping section.";
LBL1 = "SimpleSim001";
LBL2 = "SimpleSim002";
LBL3 = "SimpleSim003";
LBL4 = "SimpleSim004";
LBL5 = "SimpleSim005";

ImageThesisR10('SimpleSequence',...
                    {PW1,PW2,PW3,PW4,PW5},...
                    {SC1,SC2,SC3,SC4,SC5},...    
                    {LBL1,LBL2,LBL3,LBL4,LBL5},...
                    'test',...
                    '../imgperm',...
                    0.45,...
                    [5,1],...
                    'ht',...
                    true);
%--------------------------------------------------------------------------------------
PW1 = "../imgperm/main_HSV2GradientSimp001.png";
PW2 = "../imgperm/main_HSV2GradientSimp002.png";
SC1 = "HSV Color map of 30 degrees. The blue arrow is a vector pointing the same direction";
SC2 = "HSV Color map of 330 degrees. The blue arrow is a vector pointing the same direction";
LBL1 = "SimpleSim001";
LBL2 = "SimpleSim002";

ImageThesisR10('main_HSV2GradientSimp',...
                    {PW1,PW2},...
                    {SC1,SC2},...    
                    {LBL1,LBL2},...
                    'test',...
                    '../imgperm',...
                    0.35,...
                    [1,2],...
                    'ht',...
                    true);
%--------------------------------------------------------------------------------------


%--------------------------------------------------------------------------------------
F = FigureStruct();
F.Caption = 'The setup for a simple demonstration. The particles in blue are arranged at the top and bottom of the starting point of the nozzle and aimed at the sloping sections.';
F.FigData =  {  'Name','GradientPlotLabelled',...
                                    'Scale',0.45,...
                                    'FontSize',9,...
                                    'Title', 'Dobule Cone',...
                                    'Directory','../images',...
                                    'float',false,...
                                    'placement','H';
                                    };
F.ImagesNames ={ '../imgperm/GradientPlotLabelled.png'};
FigureR9(F);
%--------------------------------------------------------------------------------------
F = FigureStruct();
F.Caption = 'The setup for a simple demonstration. The particles in blue are arranged at the top and bottom of the starting point of the nozzle and aimed at the sloping sections.';
F.FigData =  {  'Name','main_HSV2GradientLabelled',...
                                    'Scale',0.45,...
                                    'FontSize',9,...
                                    'Title', 'Dobule Cone',...
                                    'Directory','../images',...
                                    'float',false,...
                                    'placement','H';
                                    };
F.ImagesNames ={ '../imgperm/main_HSV2GradientLabelled.png'};
FigureR9(F)

%--------------------------------------------------------------------------------------
F = FigureStruct();
F.Caption = 'The setup for a simple demonstration. The particles in blue are arranged at the top and bottom of the starting point of the nozzle and aimed at the sloping sections.';
F.FigData =  {  'Name','main_HSV2GradientSimp001',...
                                    'Scale',0.35,...
                                    'FontSize',9,...
                                    'Title', 'Dobule Cone',...
                                    'Directory','../images',...
                                    'float',false,...
                                    'placement','H';
                                    };
F.ImagesNames ={ '../imgperm/main_HSV2GradientSimp001.png'};
FigureR9(F)
%--------------------------------------------------------------------------------------
F = FigureStruct();
F.Caption = 'The setup for a simple demonstration. The particles in blue are arranged at the top and bottom of the starting point of the nozzle and aimed at the sloping sections.';
F.FigData =  {  'Name','main_HSV2GradientSimp002',...
                                    'Scale',0.35,...
                                    'FontSize',9,...
                                    'Title', 'Dobule Cone',...
                                    'Directory','../images',...
                                    'float',false,...
                                    'placement','H';
                                    };
F.ImagesNames ={ '../imgperm/main_HSV2GradientSimp002.png'};
FigureR9(F)

%--------------------------------------------------------------------------------------
F = FigureStruct();
F.Caption = 'The setup for a simple demonstration. The particles in blue are arranged at the top and bottom of the starting point of the nozzle and aimed at the sloping sections.';
F.FigData =  {  'Name','SimpleConfig',...
                                    'Scale',0.35,...
                                    'FontSize',9,...
                                    'Title', 'Dobule Cone',...
                                    'Directory','../images',...
                                    'float',false,...
                                    'placement','H';
                                    };
F.ImagesNames ={ '../imgperm/SimpleConfig.png'};
FigureR9(F)
%--------------------------------------------------------------------------------------
F = FigureStruct();
F.Caption = 'Flow thorugh a Converging-Diverging Nozzle HSV colorized to reflect the velocity angle.';
F.FigData =  {  'Name','FullCDFlow',...
                                    'Scale',0.35,...
                                    'FontSize',9,...
                                    'Title', 'Dobule Cone',...
                                    'Directory','../images',...
                                    'float',false,...
                                    'placement','H';
                                    };
F.ImagesNames ={ '../imgperm/FullCDFlow.png'};
FigureR9(F)
%--------------------------------------------------------------------------------------
F = FigureStruct();
F.Caption = 'Gradient Field Appication.';
F.FigData =  {  'Name','ParticleParticle',...
                                    'Scale',0.35,...
                                    'FontSize',9,...
                                    'Title', 'Dobule Cone',...
                                    'Directory','../images',...
                                    'float',false,...
                                    'placement','H';
                                    };
F.ImagesNames ={ '../imgperm/ParticleParticle.png'};
FigureR9(F)

%--------------------------------------------------------------------------------------
F = FigureStruct();
F.Caption = 'Gradient Field Appication.';
F.FigData =  {  'Name','GradientPlot',...
                                    'Scale',0.6,...
                                    'FontSize',9,...
                                    'Title', 'Dobule Cone',...
                                    'Directory','../images',...
                                    'float',false,...
                                    'placement','H';
                                    };
F.ImagesNames ={ '../imgperm/GradientPlot.png'};
FigureR9(F)
%--------------------------------------------------------------------------------------
F = FigureStruct();
F.Caption = 'Main Evaluation Application.';
F.FigData =  {  'Name','main_HSV2Gradient',...
                                    'Scale',0.6,...
                                    'FontSize',9,...
                                    'Title', 'Dobule Cone',...
                                    'Directory','../images',...
                                    'float',false,...
                                    'placement','H';
                                    };
F.ImagesNames ={ '../imgperm/main_HSV2Gradient.png'};
FigureR9(F)
%--------------------------------------------------------------------------------------
F = FigureStruct();
F.Caption = 'Actual Converging-Diverging Nozzel design.';
F.FigData =  {  'Name','InventortCDN',...
                                    'Scale',0.6,...
                                    'FontSize',9,...
                                    'Title', 'Dobule Cone',...
                                    'Directory','../images',...
                                    'float',false,...
                                    'placement','H';
                                    };
F.ImagesNames ={ '../images/InventortCDN.png'};
FigureR9(F);

%--------------------------------------------------------------------------------------
F = FigureStruct();
F.Caption = 'Converging-Diverging Nozzel design specifications.';
F.FigData =  {  'Name','InventortCDNDWG',...
                                    'Scale',0.8,...
                                    'FontSize',9,...
                                    'Title', 'Dobule Cone',...
                                    'Directory','../images',...
                                    'float',false,...
                                    'placement','H';
                                    };
F.ImagesNames ={ '../images/InventortCDNDWG.png'};
FigureR9(F);
%--------------------------------------------------------------------------------------
F = FigureStruct();
F.Caption = 'Performance plots from \textit{A GPU-based DEM approach for modelling of particulate systems.} \citep{gan2016}.';
F.FigData =  {  'Name','Perf_gan2016',...
                                    'Scale',0.4,...
                                    'FontSize',9,...
                                    'Title', 'Perfornamce Data Gan',...
                                    'Directory','../images',...
                                    'float',false,...
                                    'placement','H';
                                    };
F.ImagesNames ={ '../images/Perf_gan2016_01.png','../imgperm/Perf_gan2016_02.png'};
FigureR9(F);
%--------------------------------------------------------------------------------------
F = FigureStruct();
F.Caption = 'Double-cone Flow field schematic (after Olejniczak,Candler \& Hornung \citep{olejniczak1997}).';
F.FigData =  {  'Name','olej',...
                                    'Scale',0.4,...
                                    'FontSize',9,...
                                    'Title', 'Dobule Cone',...
                                    'Directory','../images',...
                                    'float',false,...
                                    'placement','H';
                                    };
F.ImagesNames ={ '../images/DoubleCone.png'};
FigureR9(F);
